export const dom = {
  form: document.querySelector("form"),
  searchField: document.querySelector("input"),
  dataContainer: document.querySelector("#data-container"),
  location: document.querySelector("#location"),
  todayTitle: document.querySelector("#today-title"),
  todayIcon: document.querySelector("#today-icon"),
  todayCond: document.querySelector("#today-cond"),
  todayTemp: document.querySelector("#today-temp"),
  todayMin: document.querySelector("#today-min"),
  todayMax: document.querySelector("#today-max"),
  //   weatherCond: document.querySelector("#weather-cond"),
  //   temperature: document.querySelector("#temperature"),
  humidity: document.querySelector("#humidity"),
};
