export const dom = {
  dataContainer: document.querySelector("#data-container"),
  form: document.querySelector("form"),
  searchField: document.querySelector("#location-input"),
  dataContainer: document.querySelector("#data-container"),
  location: document.querySelector("#location"),
  todayTitle: document.querySelector("#today-title"),
  todayIcon: document.querySelector("#today-icon"),
  todayCond: document.querySelector("#today-cond"),
  todayTemp: document.querySelector("#today-temp"),
  todayMin: document.querySelector("#today-min"),
  todayMax: document.querySelector("#today-max"),
  country: document.querySelector("#country"),
  humidity: document.querySelector("#humidity"),
  modal: document.querySelector(".modal"),
  modalBody: document.querySelector(".modal-body"),
  closeBtn: document.querySelectorAll(".close-btn"),
};
